// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// imagetodf
DataFrame imagetodf(NumericVector& image_matrix, NumericMatrix V, float bottom, float top, float left, float right);
RcppExport SEXP patternplot_imagetodf(SEXP image_matrixSEXP, SEXP VSEXP, SEXP bottomSEXP, SEXP topSEXP, SEXP leftSEXP, SEXP rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type image_matrix(image_matrixSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< float >::type bottom(bottomSEXP);
    Rcpp::traits::input_parameter< float >::type top(topSEXP);
    Rcpp::traits::input_parameter< float >::type left(leftSEXP);
    Rcpp::traits::input_parameter< float >::type right(rightSEXP);
    rcpp_result_gen = Rcpp::wrap(imagetodf(image_matrix, V, bottom, top, left, right));
    return rcpp_result_gen;
END_RCPP
}
