# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

imagetodf1 <- function(image_matrix, V, bottom = 0, top = 1, left = 0, right = 1) {
    .Call(`_patternplot_imagetodf1`, image_matrix, V, bottom, top, left, right)
}

imagetodf2 <- function(image_matrix, V, bottom = 0, top = 1, left = 0, right = 1) {
    .Call(`_patternplot_imagetodf2`, image_matrix, V, bottom, top, left, right)
}

imagetodf3 <- function(image_matrix, V, r1 = 1, r2 = 0, bottom = 0, top = 1, left = 0, right = 1) {
    .Call(`_patternplot_imagetodf3`, image_matrix, V, r1, r2, bottom, top, left, right)
}

imagetodf4 <- function(image_matrix, V, r2 = 3, bottom = 0, top = 1, left = 0, right = 1) {
    .Call(`_patternplot_imagetodf4`, image_matrix, V, r2, bottom, top, left, right)
}

